### ISSUE TITLE
link for the backend no longer works

### ISSUE THREAD

**Issue by ibrandiay** [dhinkris/fetal-yolov3-tensorrt#1]
the weight download link for the backend no longer works. could you send it to me please. (my email: bayematay@gmail.com)

**Comment by dhinkris** [comment]
Let me know if you can access this.
http://www.mediafire.com/file/l1b96fk7j18yi7v/backend.h5/file

**Comment by ibrandiay** [comment]
very good. It works I downloaded it. thank you so much

**Comment by ibrandiay** [comment]
thank .problem solved
